title: "Dave Cole for Congress, New Jersey's 2nd District"
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions: [generate_toc, smart]

exclude:
  - readme.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - script
  - CNAME
